---
# tasks file for CREATEEC2
- name : "Read env variable files"
  include_vars : 
    file : "vars/{{ PROJECT }}_{{ ENV }}.yml"
- name : "Read project variable files"
  include_vars :
    file : "vars/{{ PROJECT }}.yml"

- ec2:
    key_name: "{{ KEYNAME }}"
    region: "{{ REGION }}"
    instance_type: t2.micro
    image: "{{ AMI }}"
    wait: yes
    count: "{{ COUNT }}"
    vpc_subnet_id: "{{ SUBNETID }}"
    assign_public_ip: yes
    group :
      - "{{ SGNAME }}"
    instance_tags :
      Name : "Webserver"
      Project : "{{ PROJECT }}"
      Env : "{{ ENV }}"
      ManagedBy : "Ansible"

